# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
warnings_are_errors: true
latex: false
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'
bioc_required: true
bioc_use_devel: true
